spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/speed_db?characterEncoding=utf-8&userSSL=fales
    username: root
    password: root

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  servlet:
    context-path: /api
  port: 8089

