spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/speed_db?characterEncoding=utf-8&userSSL=fales
    username: root
    password: 123456

  servlet:
    multipart:
      # 最大文件大小
      max-file-size: 10240MB
      # 单次最大请求大小
      max-request-size: 10240MB

  # knife4j所需
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# 此配置项取消使用，如需修改本地文件保存路径请到 com.ncvt.speed.util.SavePath 类修改
#file-save-path: E:\\bishe\\file\\
#file-temp-path: E:\\bishe\\tempfile\\

mybatis:
  mapper-locations: classpath:mapper/*.xml
# mybatis日志打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  servlet:
    context-path: /api
  port: 8089
